### ISSUE TITLE
error in code

### ISSUE THREAD

**Issue by M-Ahadi** [delimitry/aztec_code_generator#3]
when I want to change this string to aztec code 
AQEjap7o8exPWgJQkf68f81bdMhC6HVmFRmAgbg7gJ01akJaMtU=

I get this error

 index = code_chars.get(mode).index(ch)
ValueError: 'L/L' is not in list

**Comment by delimitry** [comment]
Hi @mojtaba2424. I've updated data encoder function, check again please.
Thank you! :+1:
