### ISSUE TITLE
Binary mode : wrong second length for B/S when more than 31 bytes

### ISSUE THREAD

**Issue by jravallec** [delimitry/aztec_code_generator#4]
Hi, first of all, thank you for your work, it has been really helpfull.
I noticed that when entering the binary mode for more than 31 bytes, the first length is ok (0) but the second is not.
The specification says that in that case, it's not the number of bytes that should encoded, but the number of bytes less 31.

Best regards

**Comment by delimitry** [comment]
Thank you, @jravallec
