### ISSUE TITLE
ValueError is thrown on specific byte sequence

### ISSUE THREAD

**Issue by VladLupashevskyi** [delimitry/aztec_code_generator#7]
The following code:

```python
v = b'\xf7^\x0e\x9b\x04\xe4.\xc6D\xab\x88\x16j\xca\xea\xe3\rb\t<\r\n\xdfK\x86\xcf7\x86,\xccD\xac\x98>?\xedu\x14f\xb0L\xc2\xf1I14\x1f\xcd\x84\x0b\xfd\xd7\xe0\xb7\xbac\xce\x03q\xcbr\x97t%^\x0b_1\x0fw?\xda\xbc\xb7\x1a\x93i\xbe\x06\xd4\xf1]\xf3(\x8f'
AztecCode(v, ec_percent=30)
```

throws a following exception:

![image](https://user-images.githubusercontent.com/17516057/189790728-2f377cb6-8b3b-4ba2-8b7e-3e56c2992fb6.png)

I did a bit of debugging and it seems that `mode` in this case is `Mode.MIXED` hence the error is thrown.

It was tested on the latest version of this fork: https://github.com/dlenski/aztec_code_generator

**Comment by delimitry** [comment]
Thank you @VladLupashevskyi 👍🏻 
Fixed.

**Comment by dlenski** [comment]
@VladLupashevskyi, I'm happy for this bug to get fixed on any/all version of the library, of course, but why not report it at https://github.com/dlenski/aztec_code_generator/issues since **that is actually the version you were using** when you ran into the bug?
